import cora from "@/assets/images/items/cora.png";

export const RECOMENDATION_ITEMS = [
  {
    id: 1,
    image: cora,
    title: "Клетчатка для собак 'Кора'",
    price: "267",
    rating: 4,
    brand: "Cora Int",
    for: "Взрослые собаки",
    class: "Премиум",
    type: "Сухой корм",
    description: "",
    structure: "",
    reviews: [
      { rating: 4, name: "Ирина", review: "хороший" },
      { rating: 5, name: "Николай", review: "сойдёт" },
    ],
  },
  {
    id: 2,
    image: cora,
    title: "Клетчатка для собак 'Кора'",
    price: "267",
    rating: 4,
    brand: "Cora Int",
    for: "Взрослые собаки",
    class: "Премиум",
    type: "Сухой корм",
    description: "",
    structure: "",
    reviews: [
      { rating: 5, name: "Николай", review: "сойдёт" },
      { rating: 3, name: "Екатерина", review: "нормальный корм" },
    ],
  },
  {
    id: 3,
    image: cora,
    title: "Клетчатка для собак 'Кора'",
    price: "267",
    rating: 4,
    brand: "Cora Int",
    for: "Взрослые собаки",
    class: "Премиум",
    type: "Сухой корм",
    description: "",
    structure: "",
    reviews: [{ rating: 5, name: "Николай", review: "сойдёт" }],
  },
  {
    id: 4,
    image: cora,
    title: "Клетчатка для собак 'Кора'",
    price: "267",
    rating: 4,
    brand: "Cora Int",
    for: "Взрослые собаки",
    class: "Премиум",
    type: "Сухой корм",
    description: "",
    structure: "",
    reviews: [
      { rating: 4, name: "Ирина", review: "хороший" },
      { rating: 5, name: "Николай", review: "сойдёт" },
    ],
  },
  {
    id: 5,
    image: cora,
    title: "Клетчатка для собак 'Кора'",
    price: "267",
    rating: 4,
    brand: "Cora Int",
    for: "Взрослые собаки",
    class: "Премиум",
    type: "Сухой корм",
    description: "",
    structure: "",
    reviews: [
      { rating: 4, name: "Олег", review: "мой кот не стал есть" },
      { rating: 5, name: "Николай", review: "сойдёт" },
    ],
  },
  {
    id: 6,
    image: cora,
    title: "Клетчатка для собак 'Кора'",
    price: "267",
    rating: 4,
    brand: "Cora Int",
    for: "Взрослые собаки",
    class: "Премиум",
    type: "Сухой корм",
    description: "",
    structure: "",
    reviews: [
      { rating: 5, name: "Николай", review: "сойдёт" },
      { rating: 3, name: "Екатерина", review: "нормальный корм" },
    ],
  },
  {
    id: 7,
    image: cora,
    title: "Клетчатка для собак 'Кора'",
    price: "267",
    rating: 4,
    brand: "Cora Int",
    for: "Взрослые собаки",
    class: "Премиум",
    type: "Сухой корм",
    description: "",
    structure: "",
    reviews: [{ rating: 5, name: "Николай", review: "сойдёт" }],
  },
];
